package com.tobaccode.tobaccommendate.helpers.enums;

public enum BlendType {
    BURLEY, PERIQUE, VIRGINIA, AROMATIC_FIRE_CURED, LATAKIA, BRIGHT_LEAF, CAVENDISH, COROJO,
    CRIOLLO, DOKHA, ECUADORIAN_SUMATRA, HABANO, HABANO_2000, MADURO, ORIENTAL_TOBACCO, WHITE_BURLEY, THUOC_LAO,
    WILD_TOBACCO, TYPE_22
}
